# Generated by Django 4.0.2 on 2023-05-15 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='緯度')),
                ('longitude', models.FloatField(verbose_name='経度')),
                ('start_date', models.DateTimeField(verbose_name='開始日付')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='終了日付')),
                ('title', models.CharField(max_length=255, verbose_name='記事名')),
                ('content', models.TextField(verbose_name='コンテンツ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='画像イメージ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
